@startuml "Диаграмма вариантов использования"

' Перичисление Actor 
actor Специалист as specialist

' Перечисление всех функций
rectangle " " as rect {
    left to right direction
    usecase "Загрузка\n gerber файлов" as load_gerber 

    usecase "Регулировака\n параметров камеры" as change_camera_params
    usecase "Настройка\n экспозиции" as expouse
    usecase "Настройка\n баланаса белого" as white_balance
    usecase "Настройка\n ISO" as ISO
    usecase "Настройка\n яркости" as brightness
    usecase "Настройка\n контрастности" as contrast

    usecase "Управление проектом" as manage_project
    usecase "Создание" as create_project
    usecase "Удаление" as delete_project
    usecase "Сохранение" as save_project
    usecase "Загрузка" as load_project

    usecase "Управление\n референсом ПП" as manage_reference_PCB
    usecase "Загрузка\n референса ПП" as load_reference_PCB
    usecase "Редактировнаие\n референса ПП" as edit_reference_PCB

    usecase "Юстировка стола" as alignment

    usecase "Сканирование платы" as scan_PCB
}

' Перечисление всех связей
specialist --> load_gerber

specialist --> change_camera_params
change_camera_params <-- expouse: <extend>
change_camera_params <-- white_balance: <extend>
change_camera_params <-- ISO: <extend>
change_camera_params <-- brightness: <extend>
change_camera_params <-- contrast: <extend>

specialist --> manage_project
manage_project <-- create_project: <extend>
manage_project <-- delete_project: <extend>
manage_project <-- save_project: <extend>
manage_project <-- load_project: <extend>

specialist --> manage_reference_PCB
manage_reference_PCB <-- load_reference_PCB: <extend>
manage_reference_PCB <-- edit_reference_PCB: <extend>

specialist --> alignment

specialist --> scan_PCB

@endunl