@startuml aligment

|Пользователь|
start
:Выбрать окно\nюстировки;

|Система|
:Отобразить окно\nюстировки;

|Пользователь|
:Установить \nзначение сдвига;
repeat
:Выбрать \nнаправление сдвига;

|Система|
:Отправка запроса \nна стенд;

|Стенд|
:Осуществить сдвиг \nна заданное значение;

|Система|
:Отобразить \nновое положение;
:Обновить текущие\n координаты;

|Пользователь|
repeat while (Требуется смещение?) is (Да) not (Нет)
stop

@enduml