@startuml change

|Пользователь|
start
:Открыть окно \nнастроек камеры;

|Система|
:Отобразить окно\nнастроек камеры;

|Пользователь|
repeat
:Изменить значение\nнастроек;

|Система|
:Отобразить \nизменения настроек;

|Пользователь|
repeat while(Требуются изменения?) is (Да) not (Нет)
:Применить;

|Система|
:Сохранение настроек;
stop 

@enduml