@startuml load

|Пользователь|
start
:Открыть меню загрузки \ngerber файлов;

|Система|
:Отображение меню загрузки;

|Пользователь|
:Выбрать файл \nдля загрузки;

|Система|
:Разобрать gerber файл \nна компонеты;
:Записать полученные \nданные в файл;
stop

@enduml