@startuml delete
|Пользователь|
start
:Выбрать меню удаления проекта;

|Система|
:Отобразить меню удаления проекта;

|Пользователь|
:Выбрать проект;
:Нажать на кнопку Подтвердить;

|Система|
:Удалить выбранный \nпроект;
stop
@endumlф