@startuml load

|Пользователь|
start
:Выбрать меню открытия проекта;

|Система|
:Отобразить меню открытия проекта;

|Пользователь|
:Ввести месторасполжение проекта;
:Нажать на кнопку Подтвердить;
|Система|
:Открыть проект;
stop

@enduml