@startuml create

|Пользователь|
start
:Выбрать меню создания проекта;

|Система|
:Отобразить меню создания проекта;

|Пользователь|
:Ввести название проекта;
:Ввести месторасполжение проекта;
:Нажать на кнопку Подтвердить;
|Система|
:Создать проект с заднным именем \nи месторасположением;
:Открыть проект;
stop
@enduml