@startuml montage

|Пользователь|
start
:Открыть окно проверки \nкачества монтажа;

|Система|
:Отобразить окно проверки \nкачества монтажа;
|Пользователь|
:Выбрать изображение ПП;
|Система|
:Загрузить координаты \nкомпонентов;
repeat
:Проверить компонент \nна качество монтажа;
:Записать результат в файл;
repeat while (Компонеты остались?) is (Да) not(Нет)
:Отобразить на \nизображении результаты;
stop
@enduml