@startuml scaning

|Пользователь|
start
:Произвести\nюстировку;
:Отправить команду \nначала сканирования;

|Система|
:Вычислить координаты\nсмещений;
repeat
:Отправить координаты\n на смещение;

|Стенд|
:Выполнить\nСмещение;

|Система|
:Сделать снимок;
repeat while (Остались координаты?) is (Да) not (Нет)
:Произвести склейку\n изображений;
:Найти на изображении \nкомпоненты;
:Записать данные в файл;
:Отобразить изображение с \nнайденными компонентами;

|Пользователь|
:Подтвердить;
stop

@enduml